spring:
  mail:
    protocol: smtp                   # 邮件协议
    host: smtp.163.com               # smtp 服务器地址 （163邮箱为例）
    port: 25                         # 端口号（163邮箱为例）
    username: ${USER_NAME}           # 发送人邮箱地址
    password: ${PASS_WORD}           # 授权码
    default-encoding: utf-8          # 编码字符集
    debug: true                      # 开启debug模式用户会完整打印邮件发送过程的日志